"""Output selection and file paths for the single tracing workflow."""

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from logo_vectorizer.errors import ConfigurationError


class OutputFormat(StrEnum):
    """Output formats generated by the CLI."""

    SVG = "svg"
    PDF = "pdf"
    PNG = "png"


def validate_formats(formats: set[OutputFormat]) -> None:
    """Require a nonempty set of supported output-format members."""
    if not isinstance(formats, (set, frozenset)) or not formats:
        raise ConfigurationError("formats must be a nonempty set of OutputFormat members.")
    if any(not isinstance(value, OutputFormat) for value in formats):
        raise ConfigurationError("formats must contain only OutputFormat members.")


@dataclass(frozen=True)
class OutputPaths:
    """Resolved output paths for one input image."""

    directory: Path
    svg: Path
    pdf: Path
    png: Path
    report: Path


def parse_formats(value: str) -> set[OutputFormat]:
    """Parse a comma-separated list of output formats."""

    formats = {part.strip().lower() for part in value.split(",") if part.strip()}
    if not formats:
        raise ValueError("At least one output format must be provided.")

    try:
        return {OutputFormat(part) for part in formats}
    except ValueError as exc:
        allowed = ", ".join(item.value for item in OutputFormat)
        raise ValueError(f"Unsupported output format. Allowed values: {allowed}.") from exc


def resolve_output_paths(input_path: Path, out_dir: Path | None) -> OutputPaths:
    """Build stable output paths from the input file name."""

    base_dir = out_dir if out_dir is not None else Path.cwd() / "outputs"
    stem = input_path.stem
    directory = base_dir / stem
    return OutputPaths(
        directory=directory,
        svg=directory / f"{stem}.vector.svg",
        pdf=directory / f"{stem}.print.pdf",
        png=directory / f"{stem}.preview.png",
        report=directory / "report.json",
    )
